name: 'DevOps Library'
description: 'Sets SYSTEM_ARTIFACTSDIRECTORY cross-platform'
runs:
  using: "composite"
  steps:
    - name: Export SYSTEM_ARTIFACTSDIRECTORY
      shell: bash
      run: |
        echo "runner.temp = [${{ runner.temp }}]"

        if [ "$RUNNER_OS" == "Windows" ]; then
          SYSTEM_ARTIFACTSDIRECTORY="${{ runner.temp }}\\Artifacts"
        else
          SYSTEM_ARTIFACTSDIRECTORY="${{ runner.temp }}/Artifacts"
        fi
        
        echo "SYSTEM_ARTIFACTSDIRECTORY=$SYSTEM_ARTIFACTSDIRECTORY" >> $GITHUB_ENV
        echo "Export SYSTEM_ARTIFACTSDIRECTORY = \"$SYSTEM_ARTIFACTSDIRECTORY\""

    - name: Setup bush bundle
      shell: bash
      run: |
        script=https://raw.githubusercontent.com/devizer/test-and-build/master/install-build-tools-bundle.sh; 
        set -eu; set -o pipefail
        cd /tmp
        try1="wget -q -nv --no-check-certificate -O install-build-tools-bundle.sh $script 2>/dev/null || curl -ksSL -o install-build-tools-bundle.sh $script"
        eval $try1 || eval $try1 || eval $try1
        bash install-build-tools-bundle.sh >/dev/null
        rm -f install-build-tools-bundle.sh || true
        Say --Reset-Stopwatch
        Say "CPU: $(Get-CpuName)"
