name: 'DevOps Library'
description: 'Sets SYSTEM_ARTIFACTSDIRECTORY cross-platform'
runs:
  using: "composite"
  steps:
    - name: Export SYSTEM_ARTIFACTSDIRECTORY
      shell: bash
      run: |
        echo "runner.temp = [${{ runner.temp }}]"

        if [ "$RUNNER_OS" == "Windows" ]; then
          SYSTEM_ARTIFACTSDIRECTORY="${{ runner.temp }}\\Artifacts"
        else
          SYSTEM_ARTIFACTSDIRECTORY="${{ runner.temp }}/Artifacts"
        fi
        
        echo "SYSTEM_ARTIFACTSDIRECTORY=$SYSTEM_ARTIFACTSDIRECTORY" >> $GITHUB_ENV
        echo "Export SYSTEM_ARTIFACTSDIRECTORY = \"$SYSTEM_ARTIFACTSDIRECTORY\""

    - name: Setup bush bundle
      shell: bash
      run: |
        set -eu; set -o pipefail
        cd /tmp
        Download-File() {
          local url="$1"
          local file="$(basename "$url")"
          try1="wget -q -nv --no-check-certificate -O $file $url 2>/dev/null 1>&2 || curl -kfsSL -o $file $url 2>/dev/null 1>&2"
          eval $try1 || eval $try1 || eval $try1
        }

        Download-File "https://raw.githubusercontent.com/devizer/test-and-build/master/install-build-tools-bundle.sh"
        bash install-build-tools-bundle.sh >/dev/null
        rm -f install-build-tools-bundle.sh || true
        Say --Reset-Stopwatch
        Say "CPU: $(Get-CpuName)"

        Download-File "https://devizer.github.io/SqlServer-Version-Management/Install-SqlServer-Version-Management.ps1"
        cmd=""
        if [[ -n "$(command -v powershell)" ]]; then 
          cmd="powershell"; 
          powershell -f Install-SqlServer-Version-Management.ps1 >/dev/null &
        fi
        if [[ -n "$(command -v pwsh)" ]]; then
          cmd="pwsh"; 
          pwsh Install-SqlServer-Version-Management.ps1 >/dev/null &
        fi
        wait
        rm -f Install-SqlServer-Version-Management.ps1 || true
        [[ -n "$cmd" ]] && $cmd -c 'Write-Line -TextYellow "$((Get-Memory-Info).Description)"'


