name: 'DevOps Library'
description: 'Sets SYSTEM_ARTIFACTSDIRECTORY cross-platform'
runs:
  using: "composite"
  steps:
    - name: Export SYSTEM_ARTIFACTSDIRECTORY
      shell: bash
      run: |
        echo "runner.temp = [${{ runner.temp }}]"

        if [ "$RUNNER_OS" == "Windows" ]; then
          SYSTEM_ARTIFACTSDIRECTORY="${{ runner.temp }}\\Artifacts"
        else
          SYSTEM_ARTIFACTSDIRECTORY="${{ runner.temp }}/Artifacts"
        fi
        
        echo "SYSTEM_ARTIFACTSDIRECTORY=$SYSTEM_ARTIFACTSDIRECTORY" >> $GITHUB_ENV
        echo "SYSTEM_ARTIFACTSDIRECTORY = $SYSTEM_ARTIFACTSDIRECTORY"
